[project]
name = "job-crawler"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.9.4",
    "aiohttp>=3.12.13",
    "beautifulsoup4>=4.13.4",
    "lxml>=5.4.0"
]
